plantinformatics/pretzel

backend/common/models/client.js, backend/server/views/access_granted.ejs, frontend/app/components/form/user-signup.js, frontend/app/router.js, frontend/app/templates/access-request.hbs, frontend/app/templates/admin-verified.hbs, frontend/app/templates/components/draw-map.hbs, frontend/app/templates/components/form/user-signup.hbs, frontend/package.json
Main change is 
* addition of two step user verification process for subscription, via email
This version is running on the dev instance and can be tested there.
=> Candidate for merge to master and update on main instance

frontend/app/styles/app.scss
Tested OK, using JSON file upload.
(there are some unrelated issues with pasting a TSV into the upload CSV table  and CSV file upload - adds block but features are not returned by API, feature count is OK,   this looks to be because of NaN in the domain in the request, e.g :  api/Blocks/blockFeaturesInterval?blocks[]=5e154a6959b761263998eb4b&intervals[axes][0][domain][]=NaN ...,  I'll follow that up.
=> Fixes left panel overflow issue

frontend/app/components/draw/block-adj.js, frontend/app/models/block-adj.js, frontend/app/templates/components/draw/block-adj.hbs, frontend/app/templates/mapview.hbs, frontend/app/utils/draw/paths-filter.js, frontend/app/utils/draw/zoomPanCalcs.js, frontend/app/utils/interval-calcs.js, frontend/app/utils/paths-api.js, frontend/package.json, package.json
=> Master release v2.2.1

frontend/app/controllers/login.js, frontend/app/routes/login.js
Includes commit 28be8b3 which addresses an issue introduced in 6f9e598.
prevent user login form field input from being set in route URL
v2.2.2
=> Master release v2.2.2

frontend/app/components/axis-tracks.js, frontend/app/components/draw/axis-1d.js, frontend/app/components/draw/block-adj.js, frontend/app/controllers/login.js, frontend/app/models/block-adj.js, frontend/app/routes/login.js, frontend/app/templates/components/draw/block-adj.hbs, frontend/app/templates/components/panel/view-controls.hbs, frontend/app/templates/mapview.hbs, frontend/app/utils/draw/paths-filter.js, frontend/app/utils/stacks.js, frontend/package.json, package.json
update X position of path end when left adjacent axis is split
This issue, fixed by c099c38, arose during the work in v2.2.2 to .3
=> Master release v2.2.4

Dockerfile, frontend/app/components/axis-tracks.js, frontend/app/routes/application.js, frontend/app/routes/change-password.js, frontend/app/routes/login.js, frontend/app/routes/mapview.js, frontend/app/routes/matrixview.js, frontend/app/services/auth.js, frontend/app/session-stores/application.js, frontend/app/templates/components/form/api-server.hbs, frontend/app/templates/components/form/change-password.hbs, frontend/app/templates/components/form/reset-password.hbs, frontend/app/templates/components/form/user-login.hbs, frontend/app/templates/components/form/user-signup.hbs, frontend/app/templates/components/new-datasource-modal.hbs, frontend/config/environment.js, frontend/package.json, package.json
Completes some follow-on issues from #210,
and #217
=> Master Release 2.3.0

frontend/app/services/auth.js, frontend/app/session-stores/application.js, frontend/package.json, package.json
Testing so far indicates this fixes #217 
Changes : instead of modifying .cookieDomain, change hyphen to underscore in .cookieName
=> Master Release v2.3.1

frontend/app/components/axis-charts.js, frontend/app/components/axis-tracks.js, frontend/app/components/draw-map.js, frontend/app/components/draw/axes-1d.js, frontend/app/components/draw/axis-1d.js, frontend/app/components/draw/axis-ticks-selected.js, frontend/app/components/draw/block-adj.js, frontend/app/components/goto-feature-list.js, frontend/app/components/panel/feature-list.js, frontend/app/components/selected-markers.js, frontend/app/models/block.js, frontend/app/services/data/axis-zoom.js, frontend/app/services/data/heads-up.js, frontend/app/services/data/selected.js, frontend/app/styles/app.scss, frontend/app/templates/components/axis-tracks.hbs, frontend/app/templates/components/draw-map.hbs, frontend/app/templates/components/draw/axes-1d.hbs, frontend/app/utils/common/promises.js, frontend/app/utils/domElements.js, frontend/app/utils/draw/axis.js, frontend/app/utils/draw/axisBrush.js, frontend/app/utils/draw/chart1.js, frontend/app/utils/draw/collate-paths.js, frontend/app/utils/draw/d3-svg.js, frontend/app/utils/draw/viewport.js, frontend/app/utils/hover.js, frontend/package.json, package.json
#223 Selections and defining intervals
=> Master Release 2.5.0

backend/common/models/client.js, backend/common/utilities/block-features.js, backend/common/utilities/paths-aggr.js, frontend/app/components/draw/axis-1d.js, frontend/app/templates/components/suggest-link.hbs, frontend/package.json, package.json
- URL in signup verified email : use API_HOST when behind proxy (URL was localhost)
- #231 Some axis track features when clicked don't show a triangle
- axis clicked features : handle duplicate names in range filter
- blockFeaturesCounts : include bounds check on value_0 in match, to improve benefit from index
=> Master Release 2.6.1

frontend/app/components/table-brushed.js
feature table : dataForHoTable : handle results of feature search
=> Master Release v2.7.1

frontend/package.json, package.json
=> Master Release v2.7.2

frontend/app/services/data/view.js, frontend/package.json, package.json, resources/emacs_config.el
dataset explorer : initialise view history if none defined yet in this browser.
=> Master Release v2.11.2

Dockerfile, frontend/app/components/axis-charts.js, frontend/app/components/draw-map.js, frontend/app/components/draw/axes-1d.js, frontend/app/components/draw/axis-1d.js, frontend/app/components/record/entry-block-add.js, frontend/app/models/block.js, frontend/app/services/auth.js, frontend/app/utils/draw/interval-overlap.js, frontend/app/utils/draw/paths-filter.js, frontend/app/utils/interval-calcs.js, frontend/package.json, lb4app/lb3app/common/models/dataset.js, lb4app/lb3app/common/utilities/child-process.js, lb4app/lb3app/common/utilities/upload.js, lb4app/lb3app/scripts/blastn_cont.bash, lb4app/lb3app/scripts/blastn_request.bash, lb4app/lb3app/scripts/dnaSequenceLookup.bash, lb4app/lb3app/scripts/dnaSequenceSearch.bash, lb4app/lb3app/scripts/uploadSpreadsheet.bash, package.json
- remaining items from #283
- remaining items from PR #306 
- prioritised items from #216 
Branch :
- feature/groupOwn
=> Master Release v2.14.1

Dockerfile, frontend/app/services/auth.js, frontend/package-lock.json, frontend/package.json, package.json
#283 :
- fix exception (getBlockFeaturesCount() : pass id param)
- update frontend build from node 10 to 12.
Branch :
- feature/groupOwn
=> Master Release v2.14.2

frontend/app/components/axis-charts.js, frontend/app/components/draw-map.js, frontend/app/components/draw/axis-1d.js, frontend/app/components/draw/graph-frame.js, frontend/app/components/draw/stacks-view.js, frontend/app/components/panel/upload/file-drop-zone.js, frontend/app/components/panel/view-controls.js, frontend/app/models/block-adj.js, frontend/app/styles/app.scss, frontend/app/templates/components/panel/view-controls.hbs, frontend/app/utils/draw/axis-draw.js, frontend/app/utils/draw/axisBrush.js, frontend/app/utils/draw/axisTitle.js, frontend/app/utils/stacks.js, lb4app/lb3app/common/models/block.js, lb4app/lb3app/common/models/dataset.js, lb4app/lb3app/common/utilities/block-features.js, lb4app/lb3app/common/utilities/client-groups.js, lb4app/lb3app/common/utilities/spreadsheet-read.js, lb4app/lb3app/scripts/dnaSequenceSearch.bash, lb4app/lb3app/scripts/vcfGenotypeLookup.bash
This branch contains reorganisation changes (#190), which are working ok, but with some issues to be stabilised, spreadsheet  improvements, particularly in error reporting to the frontend GUI.
The aim of the PR is to track issues and prepare this branch for release.
Some improvements to sign-up may be added, [noted](https://github.com/plantinformatics/pretzel/issues/216#issuecomment-1381621090) in #216.
=> Stabilise reorganisation changes; include spreadsheet and sign-up improvements

frontend/app/components/draw/axis-ticks-selected.js, frontend/app/components/draw/graph-annotations.js, frontend/app/components/draw/graph-frame.js, frontend/app/components/panel/upload/blast-results-view.js, frontend/app/components/panel/upload/blast-results.js, frontend/app/controllers/mapview.js, frontend/app/services/auth.js, frontend/app/services/data/transient.js, frontend/package.json, package.json
fixes for :
- sign-up
- window resize axes
- display of axes for blast results
=> Master Release v2.17.4

doc/adminGuides/docker-compose.prod.yaml, doc/adminGuides/install_and_configure.md, doc/adminGuides/pretzel.compose.prod.env, frontend/app/utils/draw/zoomPanCalcs.js
Results of   #421
Also includes a mouse-wheel performance improvement in Firefox.
=> Add documentation for System administrators / installers

frontend/app/components/panel/manage-genotype.js, frontend/app/models/dataset.js, frontend/app/utils/data/vcf-feature.js, frontend/package.json, package.json
Extend Sample column sorting by selected SNPs Alt/Ref / defined haplotype to handle multiple chromosomes of a dataset.
- #501
=> Release v3.7.1

frontend/app/components/panel/manage-genotype.js, frontend/package.json, package.json
=> Release v3.7.3

frontend/app/components/panel/pan-barlex.hbs, frontend/app/components/panel/pan-barlex.js, frontend/app/templates/mapview.hbs, frontend/package.json, package.json
- #549
f389434f add feature flag options=PanBARLEX
=> Release v3.9.2 : add feature flag options=PanBARLEX

frontend/app/components/panel/pan-barlex.js, frontend/package.json, package.json
#549
- fb9c67a8 change PanBARLEX dot-plot limit 50K to 1M. update version to 3.9.4
=> Release v3.9.4 : change PanBARLEX dot-plot limit 50K to 1M. update version to 3.9.4

frontend/package.json, lb4app/lb3app/common/models/block.js, lb4app/lb3app/common/utilities/mongoDB-driver-lib.js, package.json
c489b86f in blockFeaturesInterval also handle ObjectID in .blockId
3a792c65 update version to 3.9.5
Branch : feature/panBARLEX
=> Release v3.9.5 : fix exception in QTL display

frontend/app/components/draw/axis-1d.js, frontend/app/components/draw/axis-ticks-selected.js, frontend/app/components/draw/block-adj.js, frontend/app/components/form/sample-data.hbs, frontend/app/components/form/sample-data.js, frontend/app/components/panel/manage-genotype.js, frontend/app/components/table-brushed.js, frontend/app/mixins/axis-position.js, frontend/app/services/data/paths-progressive.js, frontend/app/templates/components/table-brushed.hbs, frontend/app/utils/draw/axisBrush.js, frontend/app/utils/draw/zoomPanCalcs.js, frontend/package-lock.json, frontend/package.json, lb4app/package.json, package.json
from #563 :
- fix axis flip issues
- handle duplicates in selected sample names
- avoid exception after switching to Account Settings
- 161d4f99 update version to 3.9.7
Branch : feature/panBARLEX
=> Release v3.9.7 :  - issues from workshop practice
